### ISSUE TITLE
custom:对于主题的疑问：在halo设置了页脚用了代码注入，首页和文章中就会重新显示不会覆盖。

### ISSUE THREAD

**Issue by wshlyl** [zsjy/halo-theme-dream2.0-plus#28]
### 你当前使用的 Dream 版本

1.3.1beta

### 描述一下此定制化内容

![QQ20241010-120213](https://github.com/user-attachments/assets/15511d07-9512-424a-b224-ea85f027ac64)
1、上图就是在halo中添加页脚注入后的显示效果，内容不做修改，但是原来主题的页脚高度有些太高，平铺之后再居中个人觉得相对美观些
2.、主题现在是否支持图库。用了图库的插件，但是首页顶部菜单不显示，也无法配置。

**Comment by mjsoftking** [comment]
1. 第一个没太看懂，页脚高度是内容包裹的
2. 支持图库，添加自定义链接
![image](https://github.com/user-attachments/assets/95afe646-6825-4a74-915d-141f72086eb1)

**Comment by mjsoftking** [comment]
1. 你注入了什么，发一下看看

**Comment by wshlyl** [comment]
<div class="container">
        <ul class="footer-container footer-center">
            <li>
              <a class="logo-title" href="http://halo.ntsc.fun/" one-link-mark="yes">
                
                
                  <img class="logo-img" src="https://a.2img.org/images/2024/09/05/20240905122654.png" alt="西北技术支持中心" height="28">
                  <img class="logo-img-dark" src="https://a.2img.org/images/2024/09/05/20240905122654.png" alt="西北技术支持中心" height="28">
                
              </a>
            </li>
            <li>
              <p class="icon-spot">
                <span id="webCopyright">© 2024</span><a class="record" href="http://halo.ntsc.fun/" rel="noopener noreferrer nofollow" one-link-mark="yes">西北技术支持中心</a>
                    <a class="record" href="http://beian.miit.gov.cn/publish/query/indexFirst.action" target="_blank" rel="noopener noreferrer nofollow" one-link-mark="yes"><img src="/themes/theme-dream2-plus/assets/img/ba.webp" height="auto" width="auto" alt="备案" style="vertical-align: text-top; width: 1.2em; margin-right: 4px;">陇ICP备2024013785号-1</a>
                    <a class="record footer-truncation" href="https://beian.mps.gov.cn/#/query/webSearch?code=20240137851" target="_blank" rel="noopener noreferrer nofollow" one-link-mark="yes"><img src="/themes/theme-dream2-plus/assets/img/ga.webp" height="auto" width="auto" alt="公网安备" style="vertical-align: text-top; width: 1.2em; margin-right: 4px;">陇ICP备2024013785号-1</a></p>
                <p class="icon-spot">
                <span id="websiteDate">建站<span class="stand">63</span>天<span class="stand">00</span>时<span class="stand">31</span>分<span class="stand">57</span>秒</span>
                <span class="icon-spot footer-truncation">
                            <span id="busuanzi_container_site_uv" style="display: none">
                              <i class="ri-account-circle-line" aria-hidden="true"></i><span class="stand" id="busuanzi_value_site_uv">0</span>访客
                            </span>
                            <span id="busuanzi_container_site_pv" style="display: none">
                              <i class="ri-pie-chart-line" aria-hidden="true"></i><span class="stand" id="halo_value_site_pv">371</span>访问
                            </span>
                        </span>
              本站由<a class="cloud-driven" target="_blank" rel="noopener noreferrer nofollow" href="http://8.140.234.53:8090/" one-link-mark="yes"><img height="auto" width="auto" alt="云服务商" src="http://qiniu.ntsc.fun//LightPicture/2024/09/f32bdea2280e3566.png"></a>提供云服务</p>
            </li>
            <li>
                
            </li>
        </ul>
    </div>
就是删除了段落标签后就是下图这样显示的
![image](https://github.com/user-attachments/assets/b70f41de-a21e-4494-983d-456274e1fb1d)
我是在网站设置里添加的页脚代码注入
![image](https://github.com/user-attachments/assets/3816ee5d-25fb-411e-9045-f54982912f13)
主题那边我看了都是css和js，只有网站这里有页脚的html注入

**Comment by mjsoftking** [comment]
页脚注入只是增加一些东西或使用css、js等改变，原本存在的内容不会改变

**Comment by wshlyl** [comment]
这个完全自定义感觉不懂主题代码逻辑的，非常不好实现啊

**Comment by mjsoftking** [comment]
> 这个完全自定义感觉不懂主题代码逻辑的，非常不好实现啊

不懂代码的指定不能完全自定义，只能用默认的，或者学一学，深度的学习指定有难度，浅层一些的改一改这个界面样式还是可以的，我也是边学边改的

**Comment by mjsoftking** [comment]
https://www.hcjike.com/docs/halo-theme-dream2.0/theme/setting/basic_info
文档简单看看，就是写了一些配置项都是控制什么的
