### ISSUE TITLE
custom:刚刚测试了一个问题，设置文章置顶后最近文章列表中置顶图标不显示

### ISSUE THREAD

**Issue by wshlyl** [zsjy/halo-theme-dream2.0-plus#29]
### 你当前使用的 Dream 版本

1.3.1beta

### 描述一下此定制化内容

![QQ20241010-121428](https://github.com/user-attachments/assets/9370cbbc-49af-41be-ac11-022c11bc5ecd)
![QQ20241010-121437](https://github.com/user-attachments/assets/5f69d4d7-7169-4619-adb4-549f25485308)
效果如图，现在用的环境是win11edge浏览器，23h2版本，更换了QQ浏览器清除缓存也是一样。

**Comment by wshlyl** [comment]
问题已解决，需要在主题配置菜单中开启配置项才生效

**Comment by mjsoftking** [comment]
考虑到尽量和原主题一样，所以默认不显示了
