### ISSUE TITLE
bug:主题页脚位置的备案号和公安部备案号跳转错误了，现在点击后直接跳转到网站首页了

### ISSUE THREAD

**Issue by wshlyl** [zsjy/halo-theme-dream2.0-plus#30]
### 是什么 Halo 版本出现了此问题？

2.19

### 使用的 Dream 版本是多少？

1.3.1beta

### 在线博客地址

https://halo.ntsc.fun/

### BUG 内容

大佬。主题页脚位置的备案号和公安部备案号跳转错误了，现在点击后直接跳转到网站首页了

**Comment by mjsoftking** [comment]
使用安全链接看这个：https://www.hcjike.com/archives/WGg6Sznc

**Comment by wshlyl** [comment]
问题已解决，多谢大佬
