### ISSUE TITLE
custom:使用自定义字体不生效

### ISSUE THREAD

**Issue by wshlyl** [zsjy/halo-theme-dream2.0-plus#32]
### 你当前使用的 Dream 版本

1.31

### 描述一下此定制化内容

![image](https://github.com/user-attachments/assets/84725578-2d28-4048-b51c-ea3038b917f5)
![image](https://github.com/user-attachments/assets/dd3cfcc4-9beb-4132-ad9a-3b4344fc59da)
使用了自定义的字体，清缓存后也没有加载，
另外一个网站使用了同一个字体，效果如下
![image](https://github.com/user-attachments/assets/ae5363f1-8c29-46e3-94bf-e312183703e1)

**Comment by mjsoftking** [comment]
![image](https://github.com/user-attachments/assets/8492a355-153e-47f2-9fd3-b81ace05fa09)
生效了的

**Comment by mjsoftking** [comment]
如果你自己访问没有生效
![image](https://github.com/user-attachments/assets/1fb1bd2f-37ce-478a-b31e-84baae68fefc)
![image](https://github.com/user-attachments/assets/317e8604-90a3-48c8-bf48-707005bb39ae)
安装缓存插件时，清理缓存

![image](https://github.com/user-attachments/assets/2fcbdff1-db66-48a9-8922-5da23d008483)
勾选禁用缓存

最后 Ctrl + F5 刷新

**Comment by wshlyl** [comment]
好的，大佬，我在试试
